version: "3"
services:
  stats-summary-db:
    image: mongo
    ports:
      - "27017:27027"
    container_name: stats-summary-db
    volumes:
      - ./db/:/data/db
  stats-service:
    build:
      dockerfile: Dockerfile
      context: ./stats-service
    container_name: stats-service
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "stats-summary-db"
    volumes:
      - .:/app
      - /app/stats-service/node_modules

    env_file:
      - ./stats-service/.env
  user-service:
    build:
      dockerfile: Dockerfile
      context: ./user-service
    container_name: user-service
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "stats-summary-db"
    volumes:
      - .:/app/
      - /app/user-service/node_modules
    env_file:
      - ./user-service/.env
  gateway-service:
    build:
      dockerfile: Dockerfile
      context: ./gateway-service
    depends_on:
      - stats-service
      - user-service
    ports:
      - 80:80